(** GENERATED by tools/genbase.mjs — do not edit.
    The first mature-era anchor after the realignment: step 354540. *)

From BusyCoq Require Import Individual62 Odometer OdometerDip.
From Coq Require Import Lists.List. Import ListNotations.
Set Default Goal Selector "!".

Definition N_BASE : nat := 354540.

Definition base_left : list sym := [1;0;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;1;1;0;1;0;1;1;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;0;1;1;1;1;1;0;1;0;1;0;1;0;1;0;1;0;1;0;1;0;1;0;1;0;1;0;1;0;1;0;1;0;1;1].

Definition base_c : Q * ctape := (C, (base_left, 0%sym, [])).

Definition W_BASE : list glyph := [gf; gO; gf; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ga; ge; gO; gO; gO; gO; gO; gO; ga].
Definition N_TAIL : nat := 3.

(** 354540 machine steps, computed inside the kernel by the bare
    executor. *)
Lemma base_brun : brun N_BASE starting = Some base_c.
Proof. vm_compute. reflexivity. Qed.

Lemma base_lift : lift base_c = anchor W_BASE N_TAIL.
Proof. reflexivity. Qed.

(** Obligation 1 of 2: the base anchor is reachable from blank tape. *)
Lemma base_reach : c0 -[ tm ]->* anchor W_BASE N_TAIL.
Proof.
  rewrite <- base_lift. rewrite <- lift_starting.
  apply (brun_sound N_BASE). exact base_brun.
Qed.

(** THE ODOMETER HALTS, provided its dip orbit from the base anchor
    reaches a dying string — now the single remaining obligation. *)
Theorem odometer_halts_of_orbit : forall k W',
  dip_iter k W_BASE = Some W' ->
  dip_dies W' = true ->
  halts tm c0.
Proof.
  intros k W' Hi Hd.
  eapply halts_c0_of.
  - exact base_reach.
  - exact Hi.
  - exact Hd.
Qed.
