(* Parameter lemmas adapted from the halting-proof archive supplied by the user.
   The entire route is generated by a proved RLE parameter interpreter. *)
From BusyCoq Require Import Individual62 ES_v3.
Require Import ZifyNat Lia String List Arith NArith.
Close Scope N_scope.

Module TM1.
Definition tm := Eval compute in (TM_from_str "1RB1RF_1LC0RA_---0LD_1RE1LD_0LF0LB_1RA1LE").
Notation "c -->* c'" := (c -[ tm ]->* c') (at level 40).
Definition Phi r := 0inf {{F}}> [0] *> r.
Definition Pure n := Phi ([0;1]^^n *> 0inf).
Definition Mark a r := Phi ([0;1;0;1;1] *> [0;1]^^a *> r).
(* K m r q uses the appendix parameters (m+1,2r+1,q);
   H m s e uses the appendix parameters (m+2,s,e). *)
Definition K l m r q u := l <* [1]^^(1+m*2) {{D}}>
  [0] *> [0;1]^^(1+r*2) *> [0] *> [1]^^q *> u.
Definition H l m s e u := l <* [1]^^(1+m*2) <* [0] {{A}}>
  [0;1]^^s *> [1]^^e *> u.
Definition root := 0inf <* <[1;1;0;1;0].
Definition Z s e u := 0inf {{A}}> [0;1]^^s *> [1]^^e *> u.
Close Scope sym.
Tactic Notation "es4" constr(a) constr(b) constr(c) constr(d) "&" constr(l) constr(r) :=
  es_v3_nmp_smp
    (fun s => if (s=?"a")%string then a else if (s=?"b")%string then b
      else if (s=?"c")%string then c else if (s=?"d")%string then d else O)
    (fun s => if (s=?"l")%string then l else if (s=?"r")%string then r else (0inf)%sym).

Lemma init: c0 -->* Pure 28.
Proof. unfold Pure, Phi. esx. Qed.
Lemma Prefix n r: Phi ([0;1]^^(1+n*2) *> [1;1] *> r)%sym -->*
  Mark (1+n*2) r.
Proof. unfold Mark, Phi. es' n & r. Qed.
Lemma Entry n: Pure (2+n*2) -->* Mark (2+n*2) (0inf)%sym.
Proof. unfold Pure, Mark, Phi. es' n. Qed.
Lemma Entry2 n: Mark (2+n*2) (0inf)%sym -->*
  Mark 3 ([1]^^(2+n*4) *> [0;1] *> 0inf)%sym.
Proof. unfold Mark, Phi. es' n. Qed.
Lemma LShift l n r: (l <* <[1;0;1;0]^^n <{{D}} [0] *> r)%sym -->*
  (l <{{D}} [0] *> [1;0;1;0]^^n *> r)%sym.
Proof. es' n & l r. Qed.
Lemma KLoop l m r q u: K l (1+m) r (3+q) u -->*
  K l m (1+r) (1+q) u.
Proof.
  unfold K.
  eapply evstep_trans.
  2: { eapply evstep_trans.
       1: apply (LShift (l <* [1]^^(1+m*2) <* [0])%sym (1+r)
         ([1;0] *> [1]^^(1+q) *> u)%sym).
       es' m r q & l u. }
  es' m r q & l u.
Qed.
Lemma QK a b r: Mark (1+a) ([1]^^(3+b) *> r)%sym -->*
  K root a 0 (1+b) r.
Proof. unfold Mark, Phi, K, root. es' a b & r. Qed.
Lemma KZ r q u: K root 0 r (1+q) u -->* Z (5+r*2) q u.
Proof. unfold K, root, Z. st. do 11 step. simpl_rotate. finish. Qed.
Lemma KHead l m r e u: K l (1+m) r (1+e) u -->* H l m (3+r*2) e u.
Proof. unfold K, H. st. do 5 step. simpl_rotate. finish. Qed.
Lemma KHeadPure l m r: K l (1+m) r 0 (0inf)%sym -->* H l m (2+r*2) 0 (0inf)%sym.
Proof. unfold K, H. st. do 5 step. simpl_rotate. finish. Qed.
Lemma KZPure r: K root 0 r 0 (0inf)%sym -->* Z (4+r*2) 0 (0inf)%sym.
Proof. unfold K, root, Z. st. do 11 step. simpl_rotate. finish. Qed.
Lemma ZOdd s e u: Z (1+s*2) (2+e) u -->*
  Phi ([0;1]^^(3+s*2) *> [1]^^e *> u)%sym.
Proof. unfold Z, Phi. es' s e & u. Qed.
Lemma ZEven s e u: halts tm (Z (2+s*2) (2+e) u).
Proof. unfold Z. es' s e & u. Qed.
Lemma ZPure s: Z (2+s*2) 0 (0inf)%sym -->* Pure (4+s*2).
Proof. unfold Z, Pure, Phi. es' s. Qed.
Lemma HLoop l m s e u: H l (1+m) (1+s*2) (2+e) u -->*
  H l m (3+s*2) e u.
Proof. unfold H. es' m s e & l u. Qed.
Lemma HRoot s e u: H root 0 (1+s*2) (2+e) u -->* Z (5+s*2) e u.
Proof.
  eapply evstep_trans; [|apply KZ].
  eapply evstep_trans.
  2: { eapply evstep_trans.
       1: apply (LShift (root <* <[1;0])%sym s
         ([1;0] *> [1]^^(1+e) *> u)%sym).
       unfold K, root. es' s e & u. }
  unfold H, root. es' s e & u.
Qed.
Lemma HEven m s e u: H root (2+m) (2+s*2) (2+e) u -->*
  Mark 3 ([1]^^(m*2) *> [0;1]^^(4+s*2) *> [1]^^e *> u)%sym.
Proof. unfold H, root, Mark, Phi. es' m s e & u. Qed.
Lemma HPureLoop l m s: H l (1+m) (2+s*2) 0 (0inf)%sym -->*
  H l m (4+s*2) 0 (0inf)%sym.
Proof.
  eapply evstep_trans; [|apply (KHeadPure l m (1+s))].
  eapply evstep_trans.
  2: { eapply evstep_trans.
       1: apply (LShift (l <* [1]^^(3+m*2) <* [0])%sym (1+s)
         ([1;0] *> 0inf)%sym).
       unfold K. es' m s & l. }
  unfold H. es' m s & l.
Qed.
Lemma HPureRoot s: H root 0 (2+s*2) 0 (0inf)%sym -->* Z (6+s*2) 0 (0inf)%sym.
Proof.
  eapply evstep_trans; [|apply (KZPure (1+s))].
  eapply evstep_trans.
  2: { eapply evstep_trans.
       1: apply (LShift (root <* <[1;0])%sym (1+s) ([1;0] *> 0inf)%sym).
       unfold K, root. es' s. }
  unfold H, root. es' s.
Qed.
Lemma KLoops l n m r q u: K l (n+m) r (1+n*2+q) u -->*
  K l m (n+r) (1+q) u.
Proof. gen m r q. ind n KLoop. Qed.
Lemma HLoops l n m s e u: H l (n+m) (1+s*2) (n*2+e) u -->*
  H l m (1+(n+s)*2) e u.
Proof.
  gen m s e. induction n; intros; [finish|].
  follow (HLoop l (n+m) s (n*2+e) u). follow (IHn m (1+s) e). finish.
Qed.
Lemma HPureLoops l n m s: H l (n+m) (2+s*2) 0 (0inf)%sym -->*
  H l m (2+(n+s)*2) 0 (0inf)%sym.
Proof.
  gen m s. induction n; intros; [finish|].
  follow (HPureLoop l (n+m) s). follow (IHn m (1+s)). finish.
Qed.
Lemma High a b r: Mark (1+a) ([1]^^(5+a*2+b) *> r)%sym -->*
  Phi ([0;1]^^(7+a*2) *> [1]^^b *> r)%sym.
Proof.
  follow (QK a (2+a*2+b) r). follow (KLoops root a 0 0 (2+b) r).
  follow (KZ a (2+b) r). applys_eq (ZOdd (2+a) b r); flia.
Qed.
Lemma HighCycle a b r: Mark (1+a) ([1]^^(7+a*2+b) *> r)%sym -->*
  Mark (7+a*2) ([1]^^b *> r)%sym.
Proof. follow (High a (2+b) r). applys_eq (Prefix (3+a) ([1]^^b *> r)%sym); flia. Qed.
Lemma HHigh m s e u: H root m (1+s*2) (4+m*2+e) u -->*
  Phi ([0;1]^^(7+(m+s)*2) *> [1]^^e *> u)%sym.
Proof.
  follow (HLoops root m 0 s (4+e) u). follow (HRoot (m+s) (2+e) u).
  applys_eq (ZOdd (2+m+s) e u); flia.
Qed.
Lemma HPure m s: H root m (2+s*2) 0 (0inf)%sym -->* Pure (8+(m+s)*2).
Proof.
  follow (HPureLoops root m 0 s). follow (HPureRoot (m+s)).
  applys_eq (ZPure (2+m+s)); flia.
Qed.
Definition stack l m s := (l <* [1]^^(1+m*2) <* [0] <* <[1;0]^^(1+s*2))%sym.
Lemma PushK l m s a b u: H l m (1+s*2) 1 ([0;1]^^(1+a) *> [1]^^(3+b) *> u)%sym -->*
  K (stack l m s) a 0 (1+b) u.
Proof. unfold H, K, stack. es4 m s a b & l u. Qed.
Lemma Bridge l m s r q u: K (stack l (1+m) s) 0 r (2+q) u -->*
  H l m (5+(s+r)*2) (1+q) u.
Proof. unfold K, H, stack. es4 m s r q & l u. Qed.
Definition Gate l m s e u := (l <* [1]^^(1+m*2) <* [0]
  <* <[1;0]^^(s*2) <* [1] {{B}}> [1;0;1] *> [1]^^e *> u)%sym.
Lemma AScan l n r: (l {{A}}> [0;1]^^n *> r)%sym -->*
  (l <* <[1;0]^^n {{A}}> r)%sym.
Proof. es' n & l r. Qed.
Lemma HGate l m s e u: H l m (2+s*2) e u -->* Gate l m s e u.
Proof.
  unfold H, Gate. replace (2+s*2) with (s*2+2) by lia.
  rewrite (lpow_add _ (s*2) 2 [0;1]%sym), Str_app_assoc.
  follow (AScan (l <* [1]^^(1+m*2) <* [0])%sym (s*2)
    ([0;1]^^2 *> [1]^^e *> u)%sym). step. finish.
Qed.
Lemma TailGate l m s f: H l m (1+s*2) 1 ([0;1]^^(1+f) *> 0inf)%sym -->*
  Gate l m s (2+f*2) ([0;1] *> 0inf)%sym.
Proof. unfold H, Gate. es' m s f & l. Qed.
Lemma Join c1 c2 c:
  c1 -->* c -> c2 -->* c -> (halts tm c1 <-> halts tm c2).
Proof. intros H1 H2. rewrite (halts_evstep_iff _ _ _ H1), (halts_evstep_iff _ _ _ H2). tauto. Qed.
Lemma Tail l m s f:
  halts tm (H l m (1+s*2) 1 ([0;1]^^(1+f) *> 0inf)%sym) <->
  halts tm (H l m (2+s*2) (2+f*2) ([0;1] *> 0inf)%sym).
Proof. eapply Join; [apply TailGate|apply HGate]. Qed.
Lemma PopGate l m s M v e u:
  H (stack l m s) (2+M) (2+v*2) (2+e) u -->*
  Gate l m s (2+M*2) ([0;1]^^(4+v*2) *> [1]^^e *> u)%sym.
Proof.
  unfold H, stack, Gate. rewrite (lpow_add _ 2 e [1]%sym), Str_app_assoc.
  es4 m s M v & l ([1]^^e *> u)%sym.
Qed.
Lemma Pop l m s M v e u:
  halts tm (H (stack l m s) (2+M) (2+v*2) (2+e) u) <->
  halts tm (H l m (2+s*2) (2+M*2) ([0;1]^^(4+v*2) *> [1]^^e *> u)%sym).
Proof. eapply Join; [apply PopGate|apply HGate]. Qed.
Definition AfterH l m e u := (l <* [1]^^(1+m*2) <* <[0;1;0] {{A}}> [1]^^e *> u)%sym.
Lemma HAfter l m e u: H l m 1 e u -->* AfterH l m e u.
Proof. unfold H, AfterH. do 2 step. finish. Qed.
Lemma Low1 m u: Mark (1+m) ([1] *> u)%sym -->* AfterH root m 0 u.
Proof. unfold Mark, Phi, AfterH, root. es' m & u. Qed.
Lemma Low2 m u: Mark (1+m) ([1;1] *> u)%sym -->* AfterH root m 1 u.
Proof. unfold Mark, Phi, AfterH, root. es' m & u. Qed.
Lemma EntryOdd m j u:
  halts tm (Mark (1+j+m) ([1]^^(1+j*2) *> u)%sym) <->
  halts tm (H root m (1+j*2) 0 u).
Proof.
  destruct j as [|j].
  - eapply Join; [apply Low1|apply HAfter].
  - apply halts_evstep_iff. follow (QK (1+j+m) (j*2) u).
    follow (KLoops root j (1+m) 0 0 u).
    applys_eq (KHead root m j 0 u); flia.
Qed.
Lemma EntryEven m j u:
  halts tm (Mark (1+j+m) ([1]^^(2+j*2) *> u)%sym) <->
  halts tm (H root m (1+j*2) 1 u).
Proof.
  destruct j as [|j].
  - eapply Join; [apply Low2|apply HAfter].
  - apply halts_evstep_iff. follow (QK (1+j+m) (1+j*2) u).
    follow (KLoops root j (1+m) 0 1 u).
    applys_eq (KHead root m j 1 u); flia.
Qed.
Lemma PushLow2 l m s a u:
  H l m (1+s*2) 1 ([0;1]^^(1+a) *> [1;1] *> u)%sym -->*
  AfterH (stack l m s) a 1 u.
Proof. unfold H, AfterH, stack. es' m s a & l u. Qed.
Lemma PushEven l m s a j u:
  halts tm (H l m (1+s*2) 1 ([0;1]^^(1+j+a) *> [1]^^(2+j*2) *> u)%sym) <->
  halts tm (H (stack l m s) a (1+j*2) 1 u).
Proof.
  destruct j as [|j].
  - eapply Join; [apply PushLow2|apply HAfter].
  - apply halts_evstep_iff. follow (PushK l m s (1+j+a) (1+j*2) u).
    follow (KLoops (stack l m s) j (1+a) 0 1 u).
    applys_eq (KHead (stack l m s) a j 1 u); flia.
Qed.
Inductive Split: side -> side -> Prop :=
| SplitTail f: Split ([0;1]^^(1+f) *> 0inf)%sym ([1]^^(f*2) *> [0;1] *> 0inf)%sym
| SplitCons a j r r': Split r r' ->
  Split ([0;1]^^(3+j+a) *> [1]^^(2+j*2) *> r)%sym
    ([1]^^(a*2) *> [0;1]^^(4+j*2) *> r')%sym.
Lemma HSplit r r': Split r r' -> forall l m s,
  halts tm (H l m (1+s*2) 1 r) <-> halts tm (H l m (2+s*2) 2 r').
Proof.
  intro E. induction E; intros.
  - rewrite (Tail l m s f). unfold H. st. reflexivity.
  - replace (3+j+a) with (1+j+(2+a)) by lia.
    rewrite (PushEven l m s (2+a) j).
    rewrite IHE. rewrite (Pop l m s a j 0 r'). unfold H. st. reflexivity.
Qed.
Lemma Nested a j r r': Split r r' ->
  halts tm (Mark (3+j+a) ([1]^^(2+j*2) *> r)%sym) <->
  halts tm (Mark 3 ([1]^^(a*2) *> [0;1]^^(4+j*2) *> r')%sym).
Proof.
  intro E. replace (3+j+a) with (1+j+(2+a)) by lia.
  rewrite (EntryEven (2+a) j).
  rewrite (HSplit _ _ E), (halts_evstep_iff _ _ _ (HEven a j 0 r')).
  reflexivity.
Qed.
Lemma HPureCat l m s n: H l m s 0 ([0;1]^^n *> 0inf)%sym = H l m (s+n) 0 (0inf)%sym.
Proof. unfold H. rewrite (lpow_add _ s n [0;1]%sym), Str_app_assoc. reflexivity. Qed.
Lemma ZPureCat s n: Z s 0 ([0;1]^^n *> 0inf)%sym = Z (s+n) 0 (0inf)%sym.
Proof. unfold Z. rewrite lpow_add, Str_app_assoc. reflexivity. Qed.
Lemma OddFinishLow m j k:
  halts tm (Mark (1+j+m) ([1]^^(1+j*2) *> [0;1]^^(1+k*2) *> 0inf)%sym) <->
  halts tm (Pure (8+(m+j+k)*2)).
Proof.
  rewrite EntryOdd, HPureCat. apply halts_evstep_iff.
  applys_eq (HPure m (j+k)); flia.
Qed.
Lemma OddFinishBoundary a k:
  halts tm (Mark (1+a) ([1]^^(3+a*2) *> [0;1]^^(1+k*2) *> 0inf)%sym) <->
  halts tm (Pure (8+(a+k)*2)).
Proof.
  apply halts_evstep_iff. follow (QK a (a*2) ([0;1]^^(1+k*2) *> 0inf)%sym).
  follow (KLoops root a 0 0 0 ([0;1]^^(1+k*2) *> 0inf)%sym).
  follow (KZ a 0 ([0;1]^^(1+k*2) *> 0inf)%sym).
  rewrite ZPureCat. applys_eq (ZPure (2+a+k)); flia.
Qed.
Lemma OddFinishHigh a k:
  halts tm (Mark (1+a) ([1]^^(5+a*2) *> [0;1]^^(1+k*2) *> 0inf)%sym) <->
  halts tm (Pure (8+(a+k)*2)).
Proof.
  apply halts_evstep_iff. follow (High a 0 ([0;1]^^(1+k*2) *> 0inf)%sym).
  change (Phi ([0;1]^^(7+a*2) *> [0;1]^^(1+k*2) *> 0inf)%sym -->* Pure (8+(a+k)*2)).
  rewrite <-Str_app_assoc, <-lpow_add. unfold Pure. finish.
Qed.
Lemma Special: Mark 27 ([1]^^52 *> [0;1] *> 0inf)%sym -->* Mark 58 (0inf)%sym.
Proof. unfold Mark, Phi. es'. Qed.
Lemma HCat l m s n e u:
  H l m s 0 ([0;1]^^n *> [1]^^e *> u)%sym = H l m (s+n) e u.
Proof. unfold H. rewrite (lpow_add _ s n [0;1]%sym), Str_app_assoc. reflexivity. Qed.
Lemma EvenMerge m j k e u:
  halts tm (Mark (2+j+m) ([1]^^(2+j*2) *> [0;1]^^(1+k) *>
    [1]^^(7+m*2+k*2+e) *> u)%sym) <->
  halts tm (Phi ([0;1]^^(11+(m+j+k)*2) *> [1]^^e *> u)%sym).
Proof.
  replace (2+j+m) with (1+j+(1+m)) by lia. rewrite EntryEven.
  apply halts_evstep_iff.
  follow (PushK root (1+m) j k (4+m*2+k*2+e) u).
  follow (KLoops (stack root (1+m) j) k 0 0 (4+m*2+e) u).
  follow (Bridge root m j k (3+m*2+e) u).
  applys_eq (HHigh m (2+j+k) e u); flia.
Qed.
Lemma OddMerge m j k e u:
  halts tm (Mark (1+j+m) ([1]^^(1+j*2) *> [0;1]^^(2+k*2) *>
    [1]^^(4+m*2+e) *> u)%sym) <->
  halts tm (Phi ([0;1]^^(9+(m+j+k)*2) *> [1]^^e *> u)%sym).
Proof.
  rewrite EntryOdd, HCat. apply halts_evstep_iff.
  applys_eq (HHigh m (1+j+k) e u); flia.
Qed.
Lemma HSmall m s j k: j <= m+2 ->
  H root m (1+s*2) (j*2) ([0;1]^^(1+k*2) *> 0inf)%sym -->*
  Pure (8+(m+s+k)*2).
Proof.
  intro E. destruct (le_dec j m) as [Hle|Hgt].
  - follow (HLoops root j (m-j) s 0 ([0;1]^^(1+k*2) *> 0inf)%sym).
    rewrite HPureCat. applys_eq (HPure (m-j) (j+s+k)); flia.
  - assert (j=m+1 \/ j=m+2) as [E1|E1] by lia; subst j.
    + follow (HLoops root m 0 s 2 ([0;1]^^(1+k*2) *> 0inf)%sym).
      follow (HRoot (m+s) 0 ([0;1]^^(1+k*2) *> 0inf)%sym).
      rewrite ZPureCat. applys_eq (ZPure (2+m+s+k)); flia.
    + follow (HHigh m s 0 ([0;1]^^(1+k*2) *> 0inf)%sym).
      change (Phi ([0;1]^^(7+(m+s)*2) *> [0;1]^^(1+k*2) *> 0inf)%sym -->* Pure (8+(m+s+k)*2)).
      rewrite <-Str_app_assoc, <-lpow_add. unfold Pure. finish.
Qed.
Lemma OddSmall m j k d f: d <= m+2 ->
  halts tm (Mark (1+j+m) ([1]^^(1+j*2) *> [0;1]^^(2+k*2) *>
    [1]^^(d*2) *> [0;1]^^(1+f*2) *> 0inf)%sym) <->
  halts tm (Pure (10+(m+j+k+f)*2)).
Proof.
  intro E. rewrite EntryOdd, HCat. apply halts_evstep_iff.
  applys_eq (HSmall m (1+j+k) d f E); flia.
Qed.
Lemma EvenMiddle m j k h f:
  halts tm (Mark (4+j+h+m) ([1]^^(2+j*2) *> [0;1]^^(1+k) *>
    [1]^^(4+k*2+h*2) *> [0;1]^^(1+f) *> 0inf)%sym) <->
  halts tm (Mark 3 ([1]^^(m*2) *> [0;1]^^(8+(j+k+h)*2) *>
    [1]^^(f*2) *> [0;1] *> 0inf)%sym).
Proof.
  replace (4+j+h+m) with (1+j+(3+h+m)) by lia. rewrite EntryEven.
  transitivity (halts tm (H root (2+m) (5+(j+k+h)*2) 1 ([0;1]^^(1+f) *> 0inf)%sym)).
  - apply halts_evstep_iff.
    follow (PushK root (3+h+m) j k (1+k*2+h*2) ([0;1]^^(1+f) *> 0inf)%sym).
    follow (KLoops (stack root (3+h+m) j) k 0 0 (1+h*2) ([0;1]^^(1+f) *> 0inf)%sym).
    follow (Bridge root (2+h+m) j k (h*2) ([0;1]^^(1+f) *> 0inf)%sym).
    applys_eq (HLoops root h (2+m) (2+j+k) 1 ([0;1]^^(1+f) *> 0inf)%sym); flia.
  - replace (5+(j+k+h)*2) with (1+(2+j+k+h)*2) by lia.
    rewrite Tail. apply halts_evstep_iff.
    applys_eq (HEven m (2+j+k+h) (f*2) ([0;1] *> 0inf)%sym); flia.
Qed.
Definition empty_stack s := (0inf <* <[1;0]^^(1+s*2))%sym.
Lemma ZPushK s a b u: Z (1+s*2) 1 ([0;1]^^(1+a) *> [1]^^(3+b) *> u)%sym -->*
  K (empty_stack s) a 0 (1+b) u.
Proof. unfold Z, K, empty_stack. es' s a b & u. Qed.
Lemma ZPushLow s a u: Z (1+s*2) 1 ([0;1]^^(1+a) *> [1;1] *> u)%sym -->*
  AfterH (empty_stack s) a 1 u.
Proof. unfold Z, AfterH, empty_stack. es' s a & u. Qed.
Lemma ZPushEven s a j u:
  halts tm (Z (1+s*2) 1 ([0;1]^^(1+j+a) *> [1]^^(2+j*2) *> u)%sym) <->
  halts tm (H (empty_stack s) a (1+j*2) 1 u).
Proof.
  destruct j as [|j].
  - eapply Join; [apply ZPushLow|apply HAfter].
  - apply halts_evstep_iff. follow (ZPushK s (1+j+a) (1+j*2) u).
    follow (KLoops (empty_stack s) j (1+a) 0 1 u).
    applys_eq (KHead (empty_stack s) a j 1 u); flia.
Qed.
Definition EmptyGate s e u := (0inf <* <[1;0]^^(s*2) <* [1] {{B}}>
  [1;0;1] *> [1]^^e *> u)%sym.
Lemma ZGate s e u: Z (2+s*2) e u -->* EmptyGate s e u.
Proof.
  unfold Z, EmptyGate. replace (2+s*2) with (s*2+2) by lia.
  rewrite (lpow_add _ (s*2) 2 [0;1]%sym), Str_app_assoc.
  follow (AScan (0inf)%sym (s*2) ([0;1]^^2 *> [1]^^e *> u)%sym). step. finish.
Qed.
Lemma EmptyPopGate s m v e u: H (empty_stack s) (2+m) (2+v*2) (2+e) u -->*
  EmptyGate s (2+m*2) ([0;1]^^(4+v*2) *> [1]^^e *> u)%sym.
Proof. unfold H, empty_stack, EmptyGate. es' s m v e & u. Qed.
Lemma EmptyPopHalt s m v e u: halts tm (H (empty_stack s) (2+m) (2+v*2) (2+e) u).
Proof.
  apply (proj2 (Join _ _ _ (EmptyPopGate s m v e u)
    (ZGate s (2+m*2) ([0;1]^^(4+v*2) *> [1]^^e *> u)%sym))).
  apply ZEven.
Qed.
Lemma Critical a m j f:
  halts tm (Mark (1+a) ([1]^^(4+a*2) *> [0;1]^^(3+j+m) *>
    [1]^^(2+j*2) *> [0;1]^^(1+f) *> 0inf)%sym).
Proof.
  eapply halts_evstep.
  2: { follow (QK a (1+a*2) ([0;1]^^(3+j+m) *> [1]^^(2+j*2) *> [0;1]^^(1+f) *> 0inf)%sym).
       follow (KLoops root a 0 0 1 ([0;1]^^(3+j+m) *> [1]^^(2+j*2) *> [0;1]^^(1+f) *> 0inf)%sym).
       apply KZ. }
  replace (a+0) with a by lia.
  replace (5+a*2) with (1+(2+a)*2) by lia.
  replace (3+j+m) with (1+j+(2+m)) by lia.
  rewrite (ZPushEven (2+a) (2+m) j), Tail. apply EmptyPopHalt.
Qed.
Lemma HalfOdd x: Nat.odd x = true -> exists j, x=1+j*2.
Proof. intro E. apply Nat.odd_spec in E. destruct E as [j E]. exists j. lia. Qed.
Lemma HalfEven x: 2<=x -> Nat.even x = true -> exists j, x=2+j*2.
Proof. intros H E. apply Nat.even_spec in E. destruct E as [j E]. exists (j-1). lia. Qed.
Lemma High_spec a b r: 1<=a -> a*2+5<=b ->
  Mark a ([1]^^b *> r)%sym -->* Mark (a*2+5) ([1]^^(b-a*2-5) *> r)%sym.
Proof. intros. applys_eq (HighCycle (a-1) (b-a*2-5) r); flia. Qed.
Lemma OddFinish_spec a b c: 1<=a -> Nat.odd b=true -> b<=a*2+3 -> Nat.odd c=true ->
  halts tm (Mark a ([1]^^b *> [0;1]^^c *> 0inf)%sym) <-> halts tm (Pure (a*2+c+5)).
Proof.
  intros Ha Hb Hbc Hc. destruct (HalfOdd _ Hb) as [j Ej], (HalfOdd _ Hc) as [k Ek].
  destruct (le_dec (1+j) a).
  - applys_eq (OddFinishLow (a-j-1) j k); flia.
  - assert (j=a \/ j=a+1) as [E|E] by lia.
    + applys_eq (OddFinishBoundary (a-1) k); flia.
    + applys_eq (OddFinishHigh (a-1) k); flia.
Qed.
Lemma EvenMerge_spec a b c d r:
  2<=a -> Nat.even b=true -> 2<=b -> b+2<=a*2 -> 1<=c -> a*2+c*2+3<=d+b ->
  halts tm (Mark a ([1]^^b *> [0;1]^^c *> [1]^^d *> r)%sym) <->
  halts tm (Phi ([0;1]^^(a*2+c*2+5) *> [1]^^(d+b-a*2-c*2-3) *> r)%sym).
Proof.
  intros Ha Hb Hb0 Hab Hc Hd. destruct (HalfEven _ Hb0 Hb) as [j Ej].
  applys_eq (EvenMerge (a-j-2) j (c-1) (d+b-a*2-c*2-3) r); flia.
Qed.
Lemma OddMerge_spec a b c d r:
  Nat.odd b=true -> b+1<=a*2 -> Nat.even c=true -> 2<=c -> a*2+3<=d+b ->
  halts tm (Mark a ([1]^^b *> [0;1]^^c *> [1]^^d *> r)%sym) <->
  halts tm (Phi ([0;1]^^(a*2+c+5) *> [1]^^(d+b-a*2-3) *> r)%sym).
Proof.
  intros Hb Hab Hc Hc0 Hd. destruct (HalfOdd _ Hb) as [j Ej], (HalfEven _ Hc0 Hc) as [k Ek].
  applys_eq (OddMerge (a-j-1) j k (d+b-a*2-3) r); flia.
Qed.
Lemma OddSmall_spec a b c d f:
  Nat.odd b=true -> b+1<=a*2 -> Nat.even c=true -> 2<=c ->
  Nat.even d=true -> 2<=d -> d+b<=a*2+3 -> Nat.odd f=true ->
  halts tm (Mark a ([1]^^b *> [0;1]^^c *> [1]^^d *> [0;1]^^f *> 0inf)%sym) <->
  halts tm (Pure (a*2+c+f+5)).
Proof.
  intros Hb Hab Hc Hc0 Hd Hd0 Had Hf.
  destruct (HalfOdd _ Hb) as [j Ej], (HalfEven _ Hc0 Hc) as [k Ek],
    (HalfEven _ Hd0 Hd) as [d' Ed], (HalfOdd _ Hf) as [f' Ef].
  applys_eq (OddSmall (a-j-1) j k (1+d') f'); flia.
Qed.
Lemma EvenMiddle_spec a b c d f:
  Nat.even b=true -> Nat.even d=true -> 2<=b -> b+4<=a*2 ->
  1<=c -> 1<=f -> c*2+2<=d -> b+d+4<=a*2+c*2 ->
  halts tm (Mark a ([1]^^b *> [0;1]^^c *> [1]^^d *> [0;1]^^f *> 0inf)%sym) <->
  halts tm (Mark 3 ([1]^^(a*2+c*2-b-d-4) *> [0;1]^^(b+d+2) *>
    [1]^^(f*2-2) *> [0;1] *> 0inf)%sym).
Proof.
  intros Hb Hd Hb0 Hab Hc Hf Hcd Hbd.
  destruct (HalfEven _ Hb0 Hb) as [j Ej]. assert (2<=d) as Hd0 by lia.
  destruct (HalfEven _ Hd0 Hd) as [d' Ed].
  applys_eq (EvenMiddle (a-j-(d'-c)-4) j (c-1) (d'-c) (f-1)); flia.
Qed.
Lemma Critical_spec a b c d f:
  1<=a -> b=a*2+2 -> Nat.even d=true -> 2<=d -> d+4<=c*2 -> 1<=f ->
  halts tm (Mark a ([1]^^b *> [0;1]^^c *> [1]^^d *> [0;1]^^f *> 0inf)%sym).
Proof.
  intros Ha Hb Hd Hd0 Hcd Hf. destruct (HalfEven _ Hd0 Hd) as [j Ej].
  applys_eq (Critical (a-1) (c-j-3) j (f-1)); flia.
Qed.
Lemma Split_spec a b r r': Nat.even b=true -> 2<=b -> b+4<=a*2 -> Split r r' ->
  Split ([0;1]^^a *> [1]^^b *> r)%sym
    ([1]^^(a*2-b-4) *> [0;1]^^(b+2) *> r')%sym.
Proof.
  intros Hb Hb0 Hab E. destruct (HalfEven _ Hb0 Hb) as [j Ej].
  applys_eq (SplitCons (a-j-3) j r r' E); flia.
Qed.
Lemma Nested_spec a b r r': Nat.even b=true -> 2<=b -> b+4<=a*2 -> Split r r' ->
  halts tm (Mark a ([1]^^b *> r)%sym) <->
  halts tm (Mark 3 ([1]^^(a*2-b-4) *> [0;1]^^(b+2) *> r')%sym).
Proof.
  intros Hb Hb0 Hab E. destruct (HalfEven _ Hb0 Hb) as [j Ej].
  applys_eq (Nested (a-j-3) j r r' E); flia.
Qed.

(* The parameter computation builds its route from C(28); no trace is stored. *)
Open Scope N_scope.
Local Notation "a && b" := (if a then b else false).
Module Engine.
(* false = 01; true = 1. Lists are in physical left-to-right order. *)
Definition word := (bool * N)%type.
Definition words := list word.
Definition cons_word (w:bool) (n:N) (xs:words) : words :=
  if N.eqb n 0 then xs else
  match xs with
  | (v,m)::ys => if Bool.eqb w v then (w,n+m)::ys else (w,n)::xs
  | [] => [(w,n)]
  end.
Fixpoint normalize (xs:words) : words :=
  match xs with [] => [] | (w,n)::xs => cons_word w n (normalize xs) end.
Definition marked xs := normalize ((false,2)::(true,1)::xs).
Definition result := (words + bool)%type.
Definition next xs : result := inl (normalize xs).
Definition next_marked xs : result := inl (marked xs).

Fixpoint split_even (xs:words) : option words :=
  match xs with
  | [(false,f)] => if N.leb 1 f then Some [(true,2*f-2);(false,1)] else None
  | (false,a)::(true,b)::xs =>
    if N.even b && N.leb 2 b && N.leb (b+4) (2*a) then
      match split_even xs with
      | Some ys => Some ((true,2*a-b-4)::(false,b+2)::ys)
      | None => None
      end
    else None
  | _ => None
  end.
Definition split_fallback xs : result :=
  match split_even xs with
  | Some ys => next_marked ((false,3)::ys)
  | None => inr false
  end.
Definition merge_fallback a b c d tail xs : result :=
  if N.leb 2 a && N.even b && N.leb 2 b && N.leb 1 c && N.leb (b+2) (2*a) &&
     N.leb (2*a+2*c+3) (d+b) then
    next ((false,2*a+2*c+5)::(true,d+b-2*a-2*c-3)::tail)
  else if N.odd b && N.leb (b+1) (2*a) && N.even c && N.leb 2 c &&
          N.leb (2*a+3) (d+b) then
    next ((false,2*a+c+5)::(true,d+b-2*a-3)::tail)
  else split_fallback xs.

Definition marked_step (xs:words) : result :=
  match xs with
  | [(false,n)] =>
    if N.leb 2 n && N.even n then
      next_marked [(false,3);(true,2*n-2);(false,1)] else inr false
  | (false,a)::(true,b)::(false,c)::tail =>
    if N.leb 1 a && N.leb (2*a+5) b then
      next_marked ((false,2*a+5)::(true,b-2*a-5)::(false,c)::tail)
    else match tail with
    | [] =>
      if N.eqb a 27 && N.eqb b 52 && N.eqb c 1 then
        next_marked [(false,58)]
      else if N.leb 1 a && N.odd b && N.leb b (2*a+3) && N.odd c then
        next [(false,2*a+c+5)]
      else split_fallback xs
    | (true,d)::tail' =>
      match tail' with
      | [(false,f)] =>
        if N.leb 1 a && N.eqb b (2*a+2) && N.even d &&
           N.leb 2 d && N.leb (d+4) (2*c) && N.leb 1 f then inr true
        else if N.odd b && N.leb (b+1) (2*a) && N.even c && N.leb 2 c &&
                N.even d && N.leb 2 d && N.leb (d+b) (2*a+3) && N.odd f then
          next [(false,2*a+c+f+5)]
        else if N.even b && N.even d && N.leb 2 b && N.leb 1 c && N.leb 1 f && N.leb (b+4) (2*a) &&
                N.leb (2*c+2) d && N.leb (b+d+4) (2*a+2*c) then
          next_marked [(false,3);(true,2*a+2*c-b-d-4);
                       (false,b+d+2);(true,2*f-2);(false,1)]
        else merge_fallback a b c d tail' xs
      | _ => merge_fallback a b c d tail' xs
      end
    | _ => inr false
    end
  | _ => inr false
  end.

Definition step (xs:words) : result :=
  match xs with
  | [(false,n)] =>
    if N.leb 2 n && N.even n then
      next_marked [(false,3);(true,2*n-2);(false,1)] else inr false
  | (false,a)::(true,b)::tail =>
    if N.eqb a 2 && N.eqb b 1 then marked_step tail
    else if N.odd a && N.leb 2 b then next_marked ((false,a)::(true,b-2)::tail)
    else inr false
  | _ => inr false
  end.
Definition check fuel : bool :=
  match Eqb.N_iter_until step (inl [(false,28)]) fuel with
  | inr true => true | _ => false
  end.

End Engine.

Close Scope N_scope.
Import Engine.
Module Refine.
Definition block (w:bool) : list Sym := if w then [1]%sym else [0;1]%sym.
Fixpoint denote (xs:words) : list Sym :=
  match xs with [] => [] | (w,n)::xs => block w ^^ N.to_nat n ++ denote xs end.

Lemma cons_word_spec w n xs :
  denote (cons_word w n xs) = block w ^^ N.to_nat n ++ denote xs.
Proof.
  unfold cons_word. destruct (N.eqb_spec n 0); [subst; reflexivity|].
  destruct xs as [|[v m] xs]; [reflexivity|].
  destruct (Bool.eqb_spec w v); [subst|reflexivity].
  cbn [denote]. rewrite N2Nat.inj_add, lpow_add, app_assoc. reflexivity.
Qed.
Lemma normalize_spec xs : denote (normalize xs) = denote xs.
Proof.
  induction xs as [|[w n] xs IH]; [reflexivity|].
  cbn [normalize]. rewrite cons_word_spec, IH. reflexivity.
Qed.
Lemma marked_spec xs :
  denote (marked xs) = [0;1;0;1;1]%sym ++ denote xs.
Proof. unfold marked. rewrite normalize_spec. reflexivity. Qed.

Lemma check_sound (P:words->Prop)
  (Hstep: forall xs, match step xs with
    | inl ys => P ys -> P xs
    | inr b => b = true -> P xs
    end) fuel : check fuel = true -> P [(false,28%N)].
Proof.
  assert (Hrun: match Eqb.N_iter_until step (inl [(false,28%N)]) fuel with
    | inl xs => P xs -> P [(false,28%N)]
    | inr b => b = true -> P [(false,28%N)] end).
  { apply Eqb.N_iter_until_spec.
    - intros xs H. specialize (Hstep xs). destruct (step xs); cbn in *; auto.
    - auto. }
  unfold check. destruct (Eqb.N_iter_until step (inl [(false,28%N)]) fuel)
    as [xs|b]; [discriminate|destruct b; auto; discriminate].
Qed.
End Refine.

Import Refine.
Open Scope N_scope.

Close Scope sym.
Definition tape_of xs := (denote xs *> 0inf)%sym.
Definition P xs := halts tm (Phi (tape_of xs)).
Definition MP xs := halts tm (Mark 0 (tape_of xs)).
Definition Post (r:result) := match r with inl xs => P xs | inr b => b=true end.
Lemma next_post xs: Post (next xs) <-> P xs.
Proof. unfold Post, next, P, tape_of. rewrite normalize_spec. reflexivity. Qed.
Lemma marked_post xs: Post (next_marked xs) <-> MP xs.
Proof. unfold Post, next_marked, P, MP, tape_of, Mark. rewrite marked_spec, Str_app_assoc. reflexivity. Qed.
Lemma even_nat n: N.even n=true -> Nat.even (N.to_nat n)=true.
Proof. intro E. apply N.even_spec in E. destruct E as [k E]. apply Nat.even_spec. exists (N.to_nat k). lia. Qed.
Lemma odd_nat n: N.odd n=true -> Nat.odd (N.to_nat n)=true.
Proof. intro E. apply N.odd_spec in E. destruct E as [k E]. apply Nat.odd_spec. exists (N.to_nat k). lia. Qed.
Ltac guards := repeat match goal with
  | H: (if ?a then ?b else false)=true |- _ => destruct a eqn:?; [|discriminate]
  | H: N.leb _ _ = true |- _ => apply N.leb_le in H
  | H: N.eqb _ _ = true |- _ => apply N.eqb_eq in H
  end.
Ltac words := unfold MP, P, tape_of in *; cbn [denote block] in *;
  repeat rewrite Str_app_assoc in *.
Ltac nsimp := repeat rewrite N2Nat.inj_add in *;
  repeat rewrite N2Nat.inj_sub in *; repeat rewrite N2Nat.inj_mul in *;
  cbn [N.to_nat] in *.

Lemma split_even_spec xs ys: split_even xs=Some ys -> Split (tape_of xs) (tape_of ys).
Proof.
  revert xs ys. fix IH 1. intros xs ys E.
  destruct xs as [|[w a] xs]; [discriminate|]. destruct w; [discriminate|].
  destruct xs as [|[w b] xs].
  - cbn [split_even] in E. destruct (N.leb 1 a) eqn:A; [|discriminate].
    inversion E; subst ys. apply N.leb_le in A.
    unfold tape_of. cbn [denote block]. repeat rewrite app_nil_r. repeat rewrite Str_app_assoc.
    change (Split ([0;1]^^(N.to_nat a) *> 0inf)%sym
      ([1]^^N.to_nat (2*a-2) *> [0;1] *> 0inf)%sym).
    nsimp. applys_eq (SplitTail (N.to_nat a-1)); flia.
  - destruct w; [|discriminate]. cbn [split_even] in E.
    destruct (N.even b && N.leb 2 b && N.leb (b+4) (2*a))%N eqn:B; [|discriminate].
    destruct (split_even xs) as [zs|] eqn:ES; [|discriminate]. inversion E; subst ys.
    guards. specialize (IH _ _ ES).
    unfold tape_of in *. cbn [denote block]. repeat rewrite Str_app_assoc.
    change (Split ([0;1]^^N.to_nat a *> [1]^^N.to_nat b *> denote xs *> 0inf)%sym
      ([1]^^N.to_nat (2*a-b-4) *> [0;1]^^N.to_nat (b+2) *> denote zs *> 0inf)%sym).
    nsimp. applys_eq (Split_spec (N.to_nat a) (N.to_nat b)
      (denote xs *> 0inf)%sym (denote zs *> 0inf)%sym); try apply even_nat; auto; flia.
Qed.

Lemma split_fallback_sound a b xs:
  Post (split_fallback ((false,a)::(true,b)::xs)) -> MP ((false,a)::(true,b)::xs).
Proof.
  unfold split_fallback. cbn [split_even].
  destruct (N.even b && N.leb 2 b && N.leb (b+4) (2*a))%N eqn:E; [|discriminate].
  destruct (split_even xs) as [ys|] eqn:ES; [|discriminate].
  rewrite marked_post. intro Hr. guards. apply split_even_spec in ES.
  words. change (halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> denote xs *> 0inf)%sym)).
  change (halts tm (Mark 3 ([1]^^N.to_nat (2*a-b-4) *> [0;1]^^N.to_nat (b+2) *> denote ys *> 0inf)%sym)) in Hr.
  nsimp. rewrite Nested_spec; try apply even_nat; try lia; eauto.
  applys_eq Hr; flia.
Qed.

Lemma even_mergeN a b c d r:
  (2<=a)%N -> N.even b=true -> (2<=b)%N -> (b+2<=2*a)%N ->
  (1<=c)%N -> (2*a+2*c+3<=d+b)%N ->
  halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *> [1]^^N.to_nat d *> r)%sym) <->
  halts tm (Phi ([0;1]^^N.to_nat (2*a+2*c+5) *> [1]^^N.to_nat (d+b-2*a-2*c-3) *> r)%sym).
Proof. intros. nsimp. applys_eq (EvenMerge_spec (N.to_nat a) (N.to_nat b) (N.to_nat c) (N.to_nat d) r); try apply even_nat; auto; flia. Qed.
Lemma odd_mergeN a b c d r:
  N.odd b=true -> (b+1<=2*a)%N -> N.even c=true -> (2<=c)%N -> (2*a+3<=d+b)%N ->
  halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *> [1]^^N.to_nat d *> r)%sym) <->
  halts tm (Phi ([0;1]^^N.to_nat (2*a+c+5) *> [1]^^N.to_nat (d+b-2*a-3) *> r)%sym).
Proof. intros. nsimp. applys_eq (OddMerge_spec (N.to_nat a) (N.to_nat b) (N.to_nat c) (N.to_nat d) r); try apply even_nat; try apply odd_nat; auto; flia. Qed.
Lemma merge_fallback_sound a b c d tail:
  Post (merge_fallback a b c d tail ((false,a)::(true,b)::(false,c)::(true,d)::tail)) ->
  MP ((false,a)::(true,b)::(false,c)::(true,d)::tail).
Proof.
  unfold merge_fallback.
  destruct (N.leb 2 a && N.even b && N.leb 2 b && N.leb 1 c && N.leb (b+2) (2*a) &&
    N.leb (2*a+2*c+3) (d+b))%N eqn:E.
  - rewrite next_post. intro Hr. guards. words.
    change (halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *> [1]^^N.to_nat d *> denote tail *> 0inf)%sym)).
    rewrite even_mergeN; auto.
  - destruct (N.odd b && N.leb (b+1) (2*a) && N.even c && N.leb 2 c &&
      N.leb (2*a+3) (d+b))%N eqn:F.
    + rewrite next_post. intro Hr. guards. words.
      change (halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *> [1]^^N.to_nat d *> denote tail *> 0inf)%sym)).
      rewrite odd_mergeN; auto.
    + apply split_fallback_sound.
Qed.
Lemma highN a b r: (1<=a)%N -> (2*a+5<=b)%N ->
  Mark (N.to_nat a) ([1]^^N.to_nat b *> r)%sym -->*
  Mark (N.to_nat (2*a+5)) ([1]^^N.to_nat (b-2*a-5) *> r)%sym.
Proof. intros. nsimp. applys_eq (High_spec (N.to_nat a) (N.to_nat b) r); flia. Qed.
Lemma finishN a b c: (1<=a)%N -> N.odd b=true -> (b<=2*a+3)%N -> N.odd c=true ->
  halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *> 0inf)%sym) <->
  halts tm (Pure (N.to_nat (2*a+c+5))).
Proof. intros. nsimp. applys_eq (OddFinish_spec (N.to_nat a) (N.to_nat b) (N.to_nat c)); try apply odd_nat; auto; flia. Qed.
Lemma entryN n: (2<=n)%N -> N.even n=true ->
  Mark (N.to_nat n) (0inf)%sym -->*
  Mark 3 ([1]^^N.to_nat (2*n-2) *> [0;1] *> 0inf)%sym.
Proof.
  intros Hn En. assert (2<=N.to_nat n)%nat as Hn' by lia.
  destruct (HalfEven _ Hn' (even_nat _ En)) as [j Ej].
  nsimp. applys_eq (Entry2 j); flia.
Qed.
Lemma pure_marked_sound n:
  (2<=n)%N -> N.even n=true ->
  Post (next_marked [(false,3);(true,2*n-2);(false,1)]) -> MP [(false,n)].
Proof.
  intros Hn En. rewrite marked_post. intro Hr. words.
  repeat rewrite app_nil_r in *. change (halts tm (Mark (N.to_nat n) (0inf)%sym)).
  eapply halts_evstep; [exact Hr|apply entryN; assumption].
Qed.
Lemma high_marked_sound a b c tail:
  (1<=a)%N -> (2*a+5<=b)%N ->
  Post (next_marked ((false,2*a+5)::(true,b-2*a-5)::(false,c)::tail)) ->
  MP ((false,a)::(true,b)::(false,c)::tail).
Proof.
  intros Ha Hb. rewrite marked_post. intro Hr. words.
  change (halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *> denote tail *> 0inf)%sym)).
  eapply halts_evstep; [exact Hr|apply highN; assumption].
Qed.
Lemma end_block_sound a b c:
  Post (if N.eqb a 27 && N.eqb b 52 && N.eqb c 1 then next_marked [(false,58)]
    else if N.leb 1 a && N.odd b && N.leb b (2*a+3) && N.odd c then next [(false,2*a+c+5)]
    else split_fallback [(false,a);(true,b);(false,c)]) -> MP [(false,a);(true,b);(false,c)].
Proof.
  destruct (N.eqb a 27 && N.eqb b 52 && N.eqb c 1) eqn:E.
  - rewrite marked_post. intro Hr. guards. subst. words. repeat rewrite app_nil_r in *.
    eapply halts_evstep; [exact Hr|exact Special].
  - destruct (N.leb 1 a && N.odd b && N.leb b (2*a+3) && N.odd c)%N eqn:F.
    + rewrite next_post. intro Hr. guards. words. repeat rewrite app_nil_r in *.
      change (halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *> 0inf)%sym)).
      rewrite finishN; auto.
    + apply split_fallback_sound.
Qed.

Close Scope sym.

Section Dispatch.
Hypothesis marked_sound: forall xs, Post (marked_step xs) -> MP xs.

Lemma step_sound xs: Post (step xs) -> P xs.
Proof.
  destruct xs as [|[w a] xs]; [discriminate|]. destruct w; [discriminate|].
  destruct xs as [|[w b] xs].
  - cbn [step]. destruct (N.leb 2 a && N.even a) eqn:E; [|discriminate].
    intro H. apply marked_post in H. guards. words.
    destruct (HalfEven (N.to_nat a) ltac:(lia) (even_nat _ E)) as [k Ek].
    change (halts tm (Mark 3 ([1]^^N.to_nat (2*a-2) *> [0;1] *> 0inf)%sym)) in H.
    change (halts tm (Pure (N.to_nat a))). nsimp. rewrite Ek in *.
    eapply halts_evstep; [exact H|]. follow (Entry k).
    applys_eq (Entry2 k); flia.
  - destruct w; [|discriminate]. cbn [step].
    destruct (N.eqb a 2 && N.eqb b 1) eqn:E.
    + guards. subst a b. intro H. apply marked_sound in H. exact H.
    + destruct (N.odd a && N.leb 2 b) eqn:E0; [|discriminate].
      intro H. apply marked_post in H. guards. words.
      destruct (HalfOdd (N.to_nat a) (odd_nat a ltac:(assumption))) as [k Ek].
      change (halts tm (Mark (N.to_nat a)
        ([1]^^N.to_nat (b-2) *> denote xs *> 0inf)%sym)) in H.
      change (halts tm (Phi ([0;1]^^N.to_nat a *> [1]^^N.to_nat b *>
        denote xs *> 0inf)%sym)). nsimp. rewrite Ek in *.
      eapply halts_evstep; [exact H|].
      replace (N.to_nat b) with (2+(N.to_nat b-2))%nat at 1 by lia.
      apply Prefix.
Qed.

Lemma computation_halts fuel: check fuel = true -> halts tm c0.
Proof.
  intro H. eapply halts_evstep; [|apply init].
  change (P [(false,28%N)]). apply (check_sound P) with (fuel:=fuel); [|exact H].
  intro xs. pose proof (step_sound xs) as HS.
  unfold Post in HS. destruct (step xs); exact HS.
Qed.
End Dispatch.

Lemma criticalN (a b c d f:N):
  (1<=a)%N -> b=(2*a+2)%N -> N.even d=true ->
  (2<=d)%N -> (d+4<=2*c)%N -> (1<=f)%N ->
  halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *>
    [1]^^N.to_nat d *> [0;1]^^N.to_nat f *> 0inf)%sym).
Proof.
  intros. applys_eq (Critical_spec (N.to_nat a) (N.to_nat b) (N.to_nat c)
    (N.to_nat d) (N.to_nat f)); try apply even_nat; auto; flia.
Qed.
Lemma smallN (a b c d f:N):
  N.odd b=true -> (b+1<=2*a)%N -> N.even c=true -> (2<=c)%N ->
  N.even d=true -> (2<=d)%N -> (d+b<=2*a+3)%N -> N.odd f=true ->
  halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *>
    [1]^^N.to_nat d *> [0;1]^^N.to_nat f *> 0inf)%sym) <->
  halts tm (Pure (N.to_nat (2*a+c+f+5))).
Proof.
  intros. nsimp. applys_eq (OddSmall_spec (N.to_nat a) (N.to_nat b) (N.to_nat c)
    (N.to_nat d) (N.to_nat f)); try (apply even_nat || apply odd_nat); auto; flia.
Qed.
Lemma middleN (a b c d f:N):
  N.even b=true -> N.even d=true -> (2<=b)%N -> (b+4<=2*a)%N ->
  (1<=c)%N -> (1<=f)%N -> (2*c+2<=d)%N -> (b+d+4<=2*a+2*c)%N ->
  halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *>
    [1]^^N.to_nat d *> [0;1]^^N.to_nat f *> 0inf)%sym) <->
  halts tm (Mark 3 ([1]^^N.to_nat (2*a+2*c-b-d-4) *>
    [0;1]^^N.to_nat (b+d+2) *> [1]^^N.to_nat (2*f-2) *> [0;1] *> 0inf)%sym).
Proof.
  intros. nsimp. applys_eq (EvenMiddle_spec (N.to_nat a) (N.to_nat b) (N.to_nat c)
    (N.to_nat d) (N.to_nat f)); try apply even_nat; auto; flia.
Qed.

Close Scope sym.

Lemma marked_step_sound xs: Post (marked_step xs) -> MP xs.
Proof.
  destruct xs as [|[w a] xs]; [discriminate|]. destruct w; [discriminate|].
  destruct xs as [|[w b] xs].
  - cbn [marked_step]. destruct (N.leb 2 a && N.even a) eqn:E; [|discriminate].
    guards. apply pure_marked_sound; assumption.
  - destruct w; [|discriminate]. destruct xs as [|[w c] tail]; [discriminate|].
    destruct w; [discriminate|]. cbn [marked_step].
    destruct (N.leb 1 a && N.leb (2*a+5) b)%N eqn:E.
    + guards. apply high_marked_sound; assumption.
    + destruct tail as [|[w d] tail].
      * apply end_block_sound.
      * destruct w; [|discriminate]. destruct tail as [|[w f] tail].
        -- apply merge_fallback_sound.
        -- destruct w; [apply merge_fallback_sound|].
           destruct tail as [|h tail]; [|apply merge_fallback_sound].
           destruct (N.leb 1 a && N.eqb b (2*a+2) && N.even d &&
             N.leb 2 d && N.leb (d+4) (2*c) && N.leb 1 f)%N eqn:C.
           ++ intros _. guards. words. repeat rewrite app_nil_r.
              change (halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *>
                [1]^^N.to_nat d *> [0;1]^^N.to_nat f *> 0inf)%sym)).
              apply criticalN; assumption.
           ++ destruct (N.odd b && N.leb (b+1) (2*a) && N.even c && N.leb 2 c &&
                N.even d && N.leb 2 d && N.leb (d+b) (2*a+3) && N.odd f)%N eqn:S.
              ** rewrite next_post. intro Hr. guards. words. repeat rewrite app_nil_r in *.
                 change (halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *>
                   [1]^^N.to_nat d *> [0;1]^^N.to_nat f *> 0inf)%sym)).
                 rewrite smallN; auto.
              ** destruct (N.even b && N.even d && N.leb 2 b && N.leb 1 c && N.leb 1 f &&
                   N.leb (b+4) (2*a) && N.leb (2*c+2) d && N.leb (b+d+4) (2*a+2*c))%N eqn:M.
                 --- rewrite marked_post. intro Hr. guards. words. repeat rewrite app_nil_r in *.
                     change (halts tm (Mark (N.to_nat a) ([1]^^N.to_nat b *> [0;1]^^N.to_nat c *>
                       [1]^^N.to_nat d *> [0;1]^^N.to_nat f *> 0inf)%sym)).
                     rewrite middleN; auto.
                 --- apply merge_fallback_sound.
Qed.

Theorem halt_of_check fuel: check fuel=true -> halts tm c0.
Proof. apply computation_halts, marked_step_sound. Qed.

Theorem halt: halts tm c0.
Proof. apply (halt_of_check 30000000%N). native_check_eq. Qed.

Print Assumptions halt.
End TM1.
